server:
  port: ${PORT:8080}
  servlet:
    context-path: /notification-ms

spring:
  profiles:
    active: ${ENVIRONMENT:local}
  datasource:
    url: jdbc:h2:mem:notification-ms
    driverClassName: org.h2.Driver
    username: admin
    password:
  h2:
    console:
      enabled: true
      path: /h2