spring:
  profiles:
    active: ${ENVIRONMENT}

server:
  port: ${PORT}
  servlet:
    context-path: /notification-ms
  error:
    include-stacktrace: never

notification:
  config:
    email:
      username: ${EMAIL_USERNAME}
      password: ${EMAIL_PASSWORD}
      host: ${EMAIL_HOST}
      port: ${EMAIL_PORT}
      protocol: ${EMAIL_PROTOCOL}
      smtp-auth: ${EMAIL_SMTPAUTH}
      starttls-enabled: ${EMAIL_STARTTLS}
      debug: ${EMAIL_DEBUG}
    sms:
      account-sid: ${ACCOUNT_SID}
      auth-token: ${AUTH_TOKEN}
